version: 2

sources:
  - name: raw_data  
    description: "Tablas crudas cargadas por el pipeline de Airflow desde PostgreSQL."
    database: "postgres"
    schema: public
    
    tables:
      - name: Persona
      - name: Solicitante
      - name: Denunciado
      - name: Denuncia
      - name: Unidad
      - name: Espacio
      - name: Espacio_Academico
      - name: Espacio_No_Academico
      - name: Tipo_Violencia
      - name: Expresion_Violencia
      - name: Suceso